config/routes.rb
GooglePlacesAutocomplete::Application.routes.draw do
  resources :locations
  root :to => 'locations#new'
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.order("id desc").page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_for(str="")
    if action_name == str
      "active"
    else
      ""
    end
  end

  def bootstap_flash
    flash_messages = []
    flash.each do |type, message|
      type = :success if type == :notice
      type = :error   if type == :alert
      text = content_tag(:div, link_to("x", "#", class: "close", data:{dismiss: "alert"}) + message, class: "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GooglePlacesAutocomplete</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="container-fluid">

    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="/">Google Places Autocomplete</a>
        <ul class="nav">
          <li class="<%= active_for('new') %>"><%= link_to "Location Demo", new_location_path %></li>
          <li class="<%= active_for('index') %>"><%= link_to "Stored Locations", locations_path %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to "Source Code", "https://github.com/fred/google_places_autocomplete", target: 'blank' %></li>
        </ul>
      </div>
    </div>

    <a href="https://github.com/fred/google_places_autocomplete">
      <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub">
    </a>
    <div class="row-fluid">
      <div class='flash'>
        <%= bootstap_flash %>
      </div>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location, html: { class: "form-horizontal" }) do |f| %>

<fieldset>
  <div class="row-fluid">

    <div class="span5">

      <div class="control-group">
        <%= f.label :address, "Address", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :address, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :location_name, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :location_name, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :phone_number, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :phone_number, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :district, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :district, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :postcode, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :postcode, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :city, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :city, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :country, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :country, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :lat, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :lat, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :lng, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :lng, class: "span12" %>
        </div>
      </div>
      <div class="control-group pull-right">
        <%= f.submit "Save Location", class: 'btn' %>
      </div>
    </div>

    <div class="span7">
      <% if @location.errors.any? %>
        <div class="notice">
          <h3>Errors</h2>
          <ul>
          <% @location.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="control-group">
        <%= label_tag :search, "Search For Address" %>
        <%= text_field_tag :location_search, nil, class: "span12 search-query", type: "search" %>
      </div>
      <%= render partial: "googlemap" %>
    </div>
  </div>
</fieldset>
<% end %>

<div class="row-fluid">
  <div class="well span12">
    <h4>Images</h4>
    <div id="place_images"></div>
  </div>
</div>

app/views/locations/_googlemap.html.erb
<div id="googlemap"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">	
<!--
  var defaultZoom = 16; // Why zoomed in? Because it looks good.
  
  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(13.731547730050778, 100.56798934936523),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('googlemap'),mapOptions);
	
	// I'm Centering the map in Bangkok
	// '13.731547730050778'
	// '100.56798934936523'
	var mylat = document.getElementById("location_lat").value;
	var mylng = document.getElementById("location_lng").value;
	if (jQuery.isEmptyObject(mylat)) {
	  var mylat = '13.731548';
	  var mylng = '100.56799';
	  var defaultZoom = 14;
	};

	// set center point of map to be of the Marker or the Default City
  var centrePoint = new google.maps.LatLng(mylat, mylng);
  map.setCenter(centrePoint);
  map.setZoom(defaultZoom); 
	
	// add a draggable marker
  marker = new google.maps.Marker({
    map: map,
    draggable: true,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35));
  marker.setIcon(defaultImage);
	
  google.maps.event.addListener(marker, 'click', toggleBounce);
	
	// create Info window for marker
  var infowindow = new google.maps.InfoWindow();
  
  // Address Autocomplete
  var input = document.getElementById('location_search');
  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);
  
	// add a drag listener to the map
	google.maps.event.addListener(marker, "dragend", function() {
		var point = marker.getPosition();
		map.panTo(point);
		document.getElementById("location_lat").value = point.lat();
		document.getElementById("location_lng").value = point.lng();
		infowindow.close();
    marker.setIcon(defaultImage);
  });
  var place;
  var photos;

  // Autocomplete Listener
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    place = autocomplete.getPlace();
    marker.setPosition(place.geometry.location);
    map.panTo(place.geometry.location);
    map.setZoom(16);
		document.getElementById("location_lat").value = place.geometry.location.lat();
		document.getElementById("location_lng").value = place.geometry.location.lng();
		
		// Sets the proper image on the marker. ie. school/hospital marker
		var image = new google.maps.MarkerImage(
        place.icon,
        new google.maps.Size(71, 71),
        new google.maps.Point(0, 0),
        new google.maps.Point(17, 34),
        new google.maps.Size(35, 35));
    marker.setIcon(image);
    marker.setPosition(place.geometry.location);

    var address = '';
    if (place.address_components) {
      address = [(place.address_components[0] &&
                  place.address_components[0].short_name || ''),
                 (place.address_components[1] &&
                  place.address_components[1].short_name || ''),
                 (place.address_components[2] &&
                  place.address_components[2].short_name || '')
                ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
    
    // Autofill the fields in the form. TODO: improve parsing of the returned JSON data.
    var address = place.address_components;
    var website = place.url;

    if (address[address.length - 1]) {
      var zipcode = address[address.length - 1].long_name;
    };
    if (address[address.length - 2]) {
      var country = address[address.length - 2].long_name;
    };
    if (address[address.length - 3]) {
      var city = address[address.length - 3].long_name;
    };
    if (address[address.length - 4]) {
      var sublocality = address[address.length - 4].long_name;
    };
    if (address[0]) {
      var streetnumber = address[0].long_name;
    };
    if (address[1]) {
      var streetname = address[1].long_name;
    };
    if (place.name) {
      var location_name = place.name;
    }
    var formatted_address = place.formatted_address;
    var formatted_phone_number = place.formatted_phone_number;
    
    if (zipcode){
      document.getElementById("location_postcode").value = zipcode;
    }
    if (city) {
      document.getElementById("location_city").value = city;
    }
    if (country) {
      document.getElementById("location_country").value = country;
    }
    if (sublocality) {
      document.getElementById("location_district").value = sublocality;
    }
    if (streetname) {
      document.getElementById("location_address").value = streetname;
    }
    if (location_name) {
      document.getElementById("location_location_name").value = location_name;
    }
    if (formatted_phone_number) {
      document.getElementById("location_phone_number").value = formatted_phone_number;
    }
    photos = place.photos;
    $('#place_images').empty();
    for (var i = 0; i < photos.length; i++) {
      var url = photos[i].getUrl({maxHeight: "1280", maxWidth: "1280"});
      $('#place_images').prepend('<img src="' + url + '"/>');
    }
  });
  
  // This is the function to animate the marker after dropping it.
  function toggleBounce() {
    if (marker.getAnimation() != null) {
      marker.setAnimation(null);
    } else {
      marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  };

//-->
</script>

<br />

app/views/locations/_googlemap_show.html.erb
<div id="map" style="width: 100%; height: 360px"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">
<!--
  var defaultZoom = 17; // Why zoomed in? Because it looks good.

  var lat = <%= @location.lat %>;
  var lng = <%= @location.lng %>;

  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(lat, lng),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('map'),mapOptions);

  // Im Centering the map in Bangkok
  // '13.731547730050778'
  // '100.56798934936523'
  var mylat = document.getElementById("location_lat").value;
  var mylng = document.getElementById("location_lng").value;
  if (jQuery.isEmptyObject(mylat)) {
    var mylat = lat;
    var mylng = lng;
  };

  // set center point of map to be of the Marker or the Default City
  var centrePoint = new google.maps.LatLng(mylat, mylng);

  map.setCenter(centrePoint);
  map.setZoom(defaultZoom);

  // add a draggable marker
  marker = new google.maps.Marker({
    map:map,
    draggable: false,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  // Set marker image
  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35)
  );
  marker.setIcon(defaultImage);

//-->
</script>

<br />

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="span11">
  <h3>Listing locations</h3>

  <table class="table table-striped">
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Date</th>
    </tr>

  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location.address, location %></td>
      <td><%= link_to location.city, location %></td>
      <td><%= location.postcode %></td>
      <td><%= location.country %></td>
      <td><%= location.lat %></td>
      <td><%= location.lng %></td>
      <td><%= location.created_at.to_s(:short) %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= link_to 'New Location', new_location_path %>
  <br />

  <div class="pagination">
    <%= paginate @locations %>
  </div>
</div>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<div class="span11">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <p>
    <b>Address:</b>
    <%= @location.address %>
  </p>

  <p>
    <b>City:</b>
    <%= @location.city %>
  </p>

  <p>
    <b>Postcode:</b>
    <%= @location.postcode %>
  </p>

  <p>
    <b>Country:</b>
    <%= @location.country %>
  </p>

  <p>
    <b>Lat:</b>
    <span id="location_lat"><%= @location.lat %></span>
  </p>

  <p>
    <b>Lng:</b>
    <span id="location_lng"><%= @location.lng %></span>
  </p>

  <%= render :partial => "googlemap_show" %>
</div>